//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.29 at 02:08:31 PM CET 
//


package eu.europa.esig.dss.compatibility.v54.jaxb.diagnostic;

import javax.xml.bind.annotation.adapters.XmlAdapter;

import eu.europa.esig.dss.compatibility.v54.jaxb.parsers.SignatureScopeTypeParser;
import eu.europa.esig.dss.compatibility.v54.validation.SignatureScopeType;

public class Adapter2
    extends XmlAdapter<String, SignatureScopeType>
{


    public SignatureScopeType unmarshal(String value) {
        return (SignatureScopeTypeParser.parse(value));
    }

    public String marshal(SignatureScopeType value) {
        return (SignatureScopeTypeParser.print(value));
    }

}
