//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.29 at 02:08:31 PM CET 
//


package eu.europa.esig.dss.compatibility.v54.jaxb.diagnostic;

import javax.xml.bind.annotation.adapters.XmlAdapter;

import eu.europa.esig.dss.compatibility.v54.jaxb.parsers.TimestampedObjectTypeParser;
import eu.europa.esig.dss.compatibility.v54.validation.TimestampedObjectType;

public class Adapter3
    extends XmlAdapter<String, TimestampedObjectType>
{


    public TimestampedObjectType unmarshal(String value) {
        return (TimestampedObjectTypeParser.parse(value));
    }

    public String marshal(TimestampedObjectType value) {
        return (TimestampedObjectTypeParser.print(value));
    }

}
